### ISSUE TITLE
NPM and Yarn for builds

### ISSUE THREAD

**Issue by diegopasten** [enonic/xp-tool-enonic-ci#1]
NPM and yarn are common tools used in builds, should be added to the image.

**Comment by VirtueMe** [comment]
I solved this with the following setup for github actions:

``` yml
name: Enonic CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build, Test and Deploy app
        uses: docker://enonic/enonic-ci:7.2
        env:
          ENONIC_CLI_REMOTE_URL: ${{ secrets.ENONIC_CLI_REMOTE_URL }}
          ENONIC_CLI_REMOTE_USER: ${{ secrets.ENONIC_CLI_REMOTE_USER }}
          ENONIC_CLI_REMOTE_PASS: ${{ secrets.ENONIC_CLI_REMOTE_PASS }}
        with:
          args: bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && export NVM_DIR=\"$HOME/.nvm\" && [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" && nvm install 12 && npm install && enonic project build && enonic app install --file build/libs/*.jar"
```
